title: Canal DevOps
subtitle: Resolvendo problemas do mundo real

description: 
  Canal DevOps é um blog que tem como objetivo difundir o conhecimento, técnicas e boas práticas. Focando em problemas do mundo real.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

logo_file: logo.png  # your profile image 

# Author details
collections:
  authors:
    output: true
  levels:
    output: true

# social links 
social_username: canaldevops
